"""User email_verified

Revision ID: 284c341ef788
Revises: 7fdbf4ff489e
Create Date: 2021-08-17 22:55:25.437812

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "284c341ef788"
down_revision = "7fdbf4ff489e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("email_verified", sa.Boolean(), nullable=True))
    op.execute("UPDATE users SET email_verified = TRUE")
    op.alter_column("users", "email_verified", nullable=False)
    op.create_index(
        op.f("ix_users_email_verified"), "users", ["email_verified"], unique=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_email_verified"), table_name="users")
    op.drop_column("users", "email_verified")
    # ### end Alembic commands ###
