"""Delete View, view_count

Revision ID: 57367419fd8a
Revises: 7a57533e6d28
Create Date: 2021-09-05 17:09:47.953106

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '57367419fd8a'
down_revision = '7a57533e6d28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('question_views')
    op.drop_column('entries', 'view_count')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entries', sa.Column('view_count', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_table('question_views',
    sa.Column('entry_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['entry_id'], ['entries.id'], name='question_views_entry_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='question_views_user_id_fkey'),
    sa.PrimaryKeyConstraint('entry_id', 'user_id', name='question_views_pkey')
    )
    # ### end Alembic commands ###
