"""Vote triggers

Revision ID: d02785e8c1b3
Revises: ce37e78cfb9f
Create Date: 2021-08-09 10:28:55.315092

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "d02785e8c1b3"
down_revision = "ce37e78cfb9f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        """
        CREATE OR REPLACE FUNCTION update_score() RETURNS TRIGGER AS $$
            BEGIN
                UPDATE entries
                    SET score = (
                        SELECT COALESCE(SUM(value), 0)
                        FROM votes
                        WHERE entry_id = COALESCE(OLD.entry_id, NEW.entry_id)
                    )
                    WHERE id = COALESCE(OLD.entry_id, NEW.entry_id);
                RETURN NULL;
            END;
        $$ LANGUAGE plpgsql;
        """
    )
    op.execute(
        """
        CREATE TRIGGER update_score_tg
        AFTER INSERT OR UPDATE OR DELETE ON votes
            FOR EACH ROW EXECUTE PROCEDURE update_score();
        """
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TRIGGER IF EXISTS update_score_tg ON votes;")
    op.execute("DROP FUNCTION IF EXISTS update_score;")
    # ### end Alembic commands ###
