version: "3"

services:
  web:
    build: ./backend
    working_dir: /app
    entrypoint: /docker-entrypoint.sh
    env_file:
      - ./backend/.env
    expose:
      - "8000"
    restart: always
    depends_on:
      - db
      - redis

  worker:
    build: ./backend
    working_dir: /app
    command: >
      sh -c "pipenv run python worker.py"
    env_file:
      - ./backend/.env
    restart: always
    depends_on:
      - db
      - redis

  nginx:
    build: .
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - certbot-root:/var/www/html
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
    depends_on:
      - web

  certbot:
    image: certbot/certbot
    command: certonly --webroot --webroot-path=/var/www/html --email o.arystanov@gmail.com --agree-tos --no-eff-email -d backpainfree.org -d www.backpainfree.org
    volumes:
        - certbot-root:/var/www/html
        - certbot-etc:/etc/letsencrypt
        - certbot-var:/var/lib/letsencrypt
    depends_on:
      - nginx

  redis:
    image: redis
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis-data:/data
    expose:
      - "6379"
    restart: always

  db:
    image: postgres:13
    volumes:
      - pg-data:/var/lib/postgresql/data
    expose:
      - "5432"
    env_file:
      - ./.db.env

volumes:
  redis-data:
  pg-data:
  certbot-root:
  certbot-etc:
  certbot-var:
