version: "3"

services:
  web:
    build: ./backend
    environment:
      - SERVER_NAME=localhost:8000

  worker:
    build: ./backend

  nginx:
    build: .
    ports:
      - "8000:80"
      - "7700:7700"
    volumes:
      - ./nginx.conf.dev:/etc/nginx/conf.d/nginx.conf
