version: "3"

services:
  web:
    working_dir: /app
    entrypoint: /docker-entrypoint.sh
    environment:
      - DB_HOST=db
      - REDIS_HOST=redis
    env_file:
      - ./backend/.env
    volumes:
      - gunicorn-socket:/run/gunicorn
      - ./backend/src/server/gunicorn.conf.py:/app/server/gunicorn.conf.py
    restart: always
    depends_on:
      - db
      - redis

  worker:
    working_dir: /app
    command: >
      sh -c "pipenv run python worker.py"
    environment:
      - DB_HOST=db
      - REDIS_HOST=redis
    env_file:
      - ./backend/.env
    restart: always
    depends_on:
      - db
      - redis

  nginx:
    restart: always
    depends_on:
      - web
    volumes:
      - gunicorn-socket:/run/gunicorn

  redis:
    image: redis:6
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis-data:/data
    expose:
      - "6379"
    restart: always

  db:
    image: postgres:13
    volumes:
      - pg-data:/var/lib/postgresql/data
    expose:
      - "5432"
    restart: always
    env_file:
      - ./.db.env

  meili:
    image: getmeili/meilisearch:latest
    ports:
      - "7700:7700"

volumes:
  redis-data:
  pg-data:
  gunicorn-socket:
