version: "3"

services:
  web:
    working_dir: /app
    entrypoint: /docker-entrypoint.sh
    env_file:
      - ./backend/.env
    expose:
      - "8000"
    restart: always
    depends_on:
      - db
      - redis

  worker:
    working_dir: /app
    command: >
      sh -c "pipenv run python worker.py"
    env_file:
      - ./backend/.env
    restart: always
    depends_on:
      - db
      - redis

  nginx:
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web

  redis:
    image: redis
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis-data:/data
    expose:
      - "6379"
    restart: always

  db:
    image: postgres:13
    volumes:
      - pg-data:/var/lib/postgresql/data
    expose:
      - "5432"
    env_file:
      - ./.db.env

volumes:
  redis-data:
  pg-data:
