"""Vote

Revision ID: 096441a06c82
Revises: d13d5751b477
Create Date: 2021-07-25 22:18:19.494913

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '096441a06c82'
down_revision = 'd13d5751b477'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('votes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_action_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.SmallInteger(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['user_actions.id'], ),
    sa.ForeignKeyConstraint(['user_action_id'], ['user_actions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_votes_user_action_id'), 'votes', ['user_action_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_votes_user_action_id'), table_name='votes')
    op.drop_table('votes')
    # ### end Alembic commands ###
