"""update_score user score

Revision ID: 356c2add5117
Revises: 5960be7c64a0
Create Date: 2021-08-16 19:16:54.245706

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "356c2add5117"
down_revision = "5960be7c64a0"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        """
        CREATE OR REPLACE FUNCTION update_score() RETURNS TRIGGER AS $$
            BEGIN
                UPDATE entries
                    SET score = (
                        SELECT COALESCE(SUM(value), 0)
                        FROM votes
                        WHERE entry_id = COALESCE(OLD.entry_id, NEW.entry_id)
                    )
                    WHERE id = COALESCE(OLD.entry_id, NEW.entry_id);
                UPDATE users
                    SET score = (
                        SELECT COALESCE(SUM(score), 0)
                        FROM entries
                        WHERE user_id = users.id
                    )
                    WHERE id = (
                        SELECT user_id
                        FROM entries
                        WHERE id = COALESCE(OLD.entry_id, NEW.entry_id)
                    );
                RETURN NULL;
            END;
        $$ LANGUAGE plpgsql;
        """
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        """
        CREATE OR REPLACE FUNCTION update_score() RETURNS TRIGGER AS $$
            BEGIN
                UPDATE entries
                    SET score = (
                        SELECT COALESCE(SUM(value), 0)
                        FROM votes
                        WHERE entry_id = COALESCE(OLD.entry_id, NEW.entry_id)
                    )
                    WHERE id = COALESCE(OLD.entry_id, NEW.entry_id);
                RETURN NULL;
            END;
        $$ LANGUAGE plpgsql;
        """
    )
    # ### end Alembic commands ###
