"""User - Timestamped fields

Revision ID: 430d5e3f249b
Revises: f2fa9c653f7b
Create Date: 2021-07-18 19:32:30.773233

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '430d5e3f249b'
down_revision = 'f2fa9c653f7b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('users', sa.Column('modified_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'modified_at')
    op.drop_column('users', 'created_at')
    # ### end Alembic commands ###
