"""Entry deleted_at

Revision ID: 6809ac08d2b5
Revises: 32dfac4961f5
Create Date: 2021-08-16 16:16:25.854215

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6809ac08d2b5'
down_revision = '32dfac4961f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entries', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_entries_deleted_at'), 'entries', ['deleted_at'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_entries_deleted_at'), table_name='entries')
    op.drop_column('entries', 'deleted_at')
    # ### end Alembic commands ###
