"""Answer nullable fields

Revision ID: 6e1481b9883b
Revises: dc31cf15bb69
Create Date: 2021-07-18 17:16:45.723425

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e1481b9883b'
down_revision = 'dc31cf15bb69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('answers', 'question_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('answers', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('answers', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('answers', 'question_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
