"""Vote rename score to value

Revision ID: 7b3e91216fa9
Revises: 096441a06c82
Create Date: 2021-07-25 22:21:21.465315

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b3e91216fa9'
down_revision = '096441a06c82'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('votes', sa.Column('value', sa.SmallInteger(), nullable=False))
    op.drop_column('votes', 'score')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('votes', sa.Column('score', sa.SMALLINT(), autoincrement=False, nullable=False))
    op.drop_column('votes', 'value')
    # ### end Alembic commands ###
