"""Question

Revision ID: 7bdf692fb915
Revises: d90b75af795b
Create Date: 2021-08-08 20:51:34.692617

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7bdf692fb915'
down_revision = 'd90b75af795b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('edited_at', sa.DateTime(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['entries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('question_tags',
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], )
    )
    op.create_index(op.f('ix_question_tags_question_id'), 'question_tags', ['question_id'], unique=False)
    op.create_index(op.f('ix_question_tags_tag_id'), 'question_tags', ['tag_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_question_tags_tag_id'), table_name='question_tags')
    op.drop_index(op.f('ix_question_tags_question_id'), table_name='question_tags')
    op.drop_table('question_tags')
    op.drop_table('questions')
    # ### end Alembic commands ###
