"""Question

Revision ID: 8309374ebc82
Revises: 1ac0fe6fbd47
Create Date: 2021-07-25 21:58:15.890812

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8309374ebc82'
down_revision = '1ac0fe6fbd47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('edited_at', sa.DateTime(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['user_actions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('question_tags',
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], )
    )
    op.create_index(op.f('ix_question_tags_question_id'), 'question_tags', ['question_id'], unique=False)
    op.create_index(op.f('ix_question_tags_tag_id'), 'question_tags', ['tag_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_question_tags_tag_id'), table_name='question_tags')
    op.drop_index(op.f('ix_question_tags_question_id'), table_name='question_tags')
    op.drop_table('question_tags')
    op.drop_table('questions')
    # ### end Alembic commands ###
