"""Tag category

Revision ID: 871a6baec501
Revises: 356c2add5117
Create Date: 2021-08-17 14:47:44.479078

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '871a6baec501'
down_revision = '356c2add5117'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tag_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.add_column('tags', sa.Column('category_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_tags_category_id'), 'tags', ['category_id'], unique=False)
    op.create_foreign_key(None, 'tags', 'tag_categories', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tags', type_='foreignkey')
    op.drop_index(op.f('ix_tags_category_id'), table_name='tags')
    op.drop_column('tags', 'category_id')
    op.drop_table('tag_categories')
    # ### end Alembic commands ###
