"""Question not null constraints, indexes

Revision ID: a8b88a2296d6
Revises: e42d397089dd
Create Date: 2021-07-18 17:24:29.442544

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8b88a2296d6'
down_revision = 'e42d397089dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('question_tags', 'question_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('question_tags', 'tag_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_question_tags_question_id'), 'question_tags', ['question_id'], unique=False)
    op.create_index(op.f('ix_question_tags_tag_id'), 'question_tags', ['tag_id'], unique=False)
    op.alter_column('questions', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('questions', 'title',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    op.alter_column('questions', 'content',
               existing_type=sa.TEXT(),
               nullable=False)
    op.create_index(op.f('ix_questions_user_id'), 'questions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_questions_user_id'), table_name='questions')
    op.alter_column('questions', 'content',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('questions', 'title',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.alter_column('questions', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_question_tags_tag_id'), table_name='question_tags')
    op.drop_index(op.f('ix_question_tags_question_id'), table_name='question_tags')
    op.alter_column('question_tags', 'tag_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('question_tags', 'question_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
