"""Comment

Revision ID: d13d5751b477
Revises: 0cc4c0d4bdc2
Create Date: 2021-07-25 22:14:40.338827

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd13d5751b477'
down_revision = '0cc4c0d4bdc2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('edited_at', sa.DateTime(), nullable=True),
    sa.Column('user_action_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['user_actions.id'], ),
    sa.ForeignKeyConstraint(['user_action_id'], ['user_actions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comments_user_action_id'), 'comments', ['user_action_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_comments_user_action_id'), table_name='comments')
    op.drop_table('comments')
    # ### end Alembic commands ###
