"""Vote unique constraints

Revision ID: d44fc041bf94
Revises: 97049da19ed1
Create Date: 2021-07-25 00:46:48.149810

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd44fc041bf94'
down_revision = '97049da19ed1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('user_answer_uc', 'answer_votes', ['user_id', 'answer_id'])
    op.create_unique_constraint('user_comment_uc', 'comment_votes', ['user_id', 'comment_id'])
    op.create_unique_constraint('user_question_uc', 'question_votes', ['user_id', 'question_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_question_uc', 'question_votes', type_='unique')
    op.drop_constraint('user_comment_uc', 'comment_votes', type_='unique')
    op.drop_constraint('user_answer_uc', 'answer_votes', type_='unique')
    # ### end Alembic commands ###
