"""Entry score index

Revision ID: 32dfac4961f5
Revises: ffed0f5f5715
Create Date: 2021-08-16 16:14:54.199784

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32dfac4961f5'
down_revision = 'ffed0f5f5715'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_entries_score'), 'entries', ['score'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_entries_score'), table_name='entries')
    # ### end Alembic commands ###
