"""Entry view_count

Revision ID: 9623d47adce2
Revises: 9d9f0538e391
Create Date: 2021-08-12 00:42:49.224717

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "9623d47adce2"
down_revision = "9d9f0538e391"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("entries", sa.Column("view_count", sa.Integer(), nullable=True))
    op.execute("UPDATE entries SET view_count = 0")
    op.alter_column("entries", "view_count", nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("entries", "view_count")
    # ### end Alembic commands ###
