name: Deploy with github packages
on:
  push:
    branches:
      - master

env:
  REGISTRY: ghcr.io
  REPO_NAME: ${{ github.repository }}

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: healthqa
          POSTGRES_PASSWORD: healthqa
          POSTGRES_DB: healthqa
        ports: ['5432:5432']
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        working-directory: ./backend
        run: |
          python -m pip install --upgrade pip
          python -m pip install pipenv
          pipenv install --dev
          export PIPENV_PIPFILE=/Pipfile

      - name: Lint with flake8
        working-directory: ./backend/src
        run: |
          pipenv run flake8 . --count

      - name: Run pytest
        working-directory: ./backend/src
        run: |
          pipen run pytest -x

  build-and-deploy:
    runs-on: ubuntu-latest
    needs: test
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to the Container registry
        uses: docker/login-action@v1.10.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          driver: docker-container

      - name: Build and push app
        uses: docker/build-push-action@v2.7.0
        with:
          context: ./backend
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.REPO_NAME }}/app:latest
          cache-from: type=registry,ref=${{ env.REGISTRY }}/${{ env.REPO_NAME }}/app:buildcache
          cache-to: type=registry,ref=${{ env.REGISTRY }}/${{ env.REPO_NAME }}/app:buildcache,mode=max

      - name: Build and push nginx
        uses: docker/build-push-action@v2.7.0
        with:
          context: .
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.REPO_NAME }}/nginx:latest
          cache-from: type=registry,ref=${{ env.REGISTRY }}/${{ env.REPO_NAME }}/nginx:buildcache
          cache-to: type=registry,ref=${{ env.REGISTRY }}/${{ env.REPO_NAME }}/nginx:buildcache,mode=max

      - name: Deploy
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_KEY }}
          script: |
            cd /srv/healthqa
            git pull
            docker login ${{ env.REGISTRY }} -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}
            docker-compose -f docker-compose.yml -f docker-compose.prod.yml pull
            docker-compose -f docker-compose.yml -f docker-compose.prod.yml up -d
